### ISSUE TITLE
Not able to load up the tar.gz image file on to my raspberry pi from my SD

### ISSUE THREAD

**Issue by michaelcalve** [seemoo-lab/bcm-rpi3#25]
Hi,

Could you give some more detail on how to setup the SD card so that when I plug it into the RPi3 it will read the files on it?

I'm not sure what's going on with "e.g.: dd if=nexmon_rpi_12-10-2016.dd of=/dev/mmcblk0 bs=1M note: the sd card device (in this example mmcblk0) may change depending on your setup"

Update:  I unpacked the tar.gz file using 7-Zip and now I am copying it to the flash drive.  However, I'm seeing some other people using WinDiskManager for writing .img files to the SD card.  What's the best way to do this???

Update2:  I'm in, now we're trying to get into wireshark so we can save a pcap and analyze the packets its picking up!  Any ideas!!??

**Comment by michaelcalve** [comment]
Is it possible to use something like WireShark to capture the results and manipulate the data that's being collected from being in monitor mode!?!

**Comment by DanielAW** [comment]
Hi,
I'm glad it worked for you in the end. It is possible to capture data with `tcpdump` on the RPI3 and then copy the resulting `.pcap` file to your PC where you can open it with Wireshark. Save the captured data to a pcap file using tcpdump as follows: `tcpdump -i wlan0 -s0 -w /root/mydump.pcap`.

I will close this issue for now because the original problem seems solved.

**Comment by michaelcalve** [comment]
Thanks!
